import { expect, it } from "vitest";
import { unrendered } from "../../ui/test/helpers.ts";
import * as index from "../src/index.svelte.ts";

/** Svelte compiles a `.svelte` file only where something instantiates
 * it, so a part no test mounts is a part nothing compiles. */
it("renders every component it exports", () => {
  const components = Object.keys(index).filter((name) => /^[A-Z]/.test(name));
  expect(components.length).toBeGreaterThan(50);
  const rendered = (name: string) => new RegExp(`<${name}[\\s/>]`);
  expect(unrendered(import.meta.dirname, components, rendered)).toBe("");
});

it("exports its public names", () => {
  expect(Object.keys(index).sort()).toMatchInlineSnapshot(`
    [
      "AccordionItem",
      "AccordionItemContent",
      "AccordionItemIndicator",
      "AccordionItemTrigger",
      "AccordionRoot",
      "AccordionRootProvider",
      "CollapsibleContent",
      "CollapsibleIndicator",
      "CollapsibleRoot",
      "CollapsibleRootProvider",
      "CollapsibleTrigger",
      "ComboboxClearTrigger",
      "ComboboxContent",
      "ComboboxControl",
      "ComboboxInput",
      "ComboboxItem",
      "ComboboxItemGroup",
      "ComboboxItemGroupLabel",
      "ComboboxItemIndicator",
      "ComboboxItemText",
      "ComboboxLabel",
      "ComboboxList",
      "ComboboxPositioner",
      "ComboboxRoot",
      "ComboboxRootProvider",
      "ComboboxTrigger",
      "DialogCloseTrigger",
      "DialogContent",
      "DialogDescription",
      "DialogPositioner",
      "DialogRoot",
      "DialogRootProvider",
      "DialogTitle",
      "DialogTrigger",
      "ListboxContent",
      "ListboxItem",
      "ListboxItemGroup",
      "ListboxItemGroupLabel",
      "ListboxItemIndicator",
      "ListboxItemText",
      "ListboxLabel",
      "ListboxRoot",
      "ListboxRootProvider",
      "MenuContent",
      "MenuItem",
      "MenuItemGroup",
      "MenuItemGroupLabel",
      "MenuPositioner",
      "MenuRoot",
      "MenuRootProvider",
      "MenuSeparator",
      "MenuTrigger",
      "MenuTriggerItem",
      "PopoverCloseTrigger",
      "PopoverContent",
      "PopoverDescription",
      "PopoverIndicator",
      "PopoverPositioner",
      "PopoverRoot",
      "PopoverRootProvider",
      "PopoverTitle",
      "PopoverTrigger",
      "SelectClearTrigger",
      "SelectContent",
      "SelectControl",
      "SelectHiddenSelect",
      "SelectIndicator",
      "SelectItem",
      "SelectItemGroup",
      "SelectItemGroupLabel",
      "SelectItemIndicator",
      "SelectItemText",
      "SelectLabel",
      "SelectList",
      "SelectPositioner",
      "SelectRoot",
      "SelectRootProvider",
      "SelectTrigger",
      "SelectValueText",
      "TooltipContent",
      "TooltipPositioner",
      "TooltipRoot",
      "TooltipRootProvider",
      "TooltipTrigger",
      "collection",
      "createAccordion",
      "createCollapsible",
      "createCombobox",
      "createDialog",
      "createListbox",
      "createMenu",
      "createPopover",
      "createSelect",
      "createTooltip",
      "gridCollection",
      "useAccordionContext",
      "useAccordionItemContext",
      "useCollapsibleContext",
      "useComboboxContext",
      "useDialogContext",
      "useItemContext",
      "useListboxContext",
      "useMenuContext",
      "usePopoverContext",
      "useSelectContext",
      "useTooltipContext",
    ]
  `);
});
