import { defineConfig } from "vite";
import { globSync } from "node:fs";
import { resolve } from "node:path";

export default defineConfig({
  build: {
    lib: {
      // One entry per public module: the element + every font module
      // (generated by scripts/generate-fonts.mjs) stays individually
      // importable and tree-shakeable.
      entry: Object.fromEntries(
        [
          resolve(import.meta.dirname, "src/index.ts"),
          ...globSync(resolve(import.meta.dirname, "src/fonts/*.ts")),
        ].map((file) => [
          file.replace(/^.*src\//, "").replace(/\.ts$/, ""),
          resolve(import.meta.dirname, file),
        ]),
      ),
      formats: ["es"],
    },
    sourcemap: true,
    target: "es2022",
    rollupOptions: { external: ["monowind"] },
  },
  test: {
    environment: "happy-dom",
    globals: true,
  },
});
